default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password:
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: climatech_development

test:
  <<: *default
  database: climatech_test

production:
  <<: *default
  database: climatech_production
  username: root
  password: 90Mysql09
